---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-httpd
  namespace: exastro-gateway
spec:
  selector:
    matchLabels:
      name: gateway-httpd
  replicas: 1
  template:
    metadata:
      labels:
        name: gateway-httpd
    spec:
      volumes:
      - name: gateway-httpd-conf
        configMap:
          name: gateway-httpd-conf
      containers:
      - name: gateway-httpd
        image: exastro/exastro-gateway:0.0.1_20211004_1200
        volumeMounts:
        - name: gateway-httpd-conf
          mountPath: /etc/httpd/conf.d/exastroSettings/

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-httpd
  labels:
    app: gateway-httpd
  namespace: exastro-gateway
spec:
  ports:
  - name: http
    port: 31181
    targetPort: 31181
    nodePort: 31181
  selector:
    name: gateway-httpd
  type: NodePort
