apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-httpd-conf
  namespace: exastro-gateway
data:
  gateway-httpd.conf: |
    Listen {{ client_port }}

    <VirtualHost *:{{ client_port }}>

      SSLEngine on
      SSLCertificateFile /etc/pki/tls/certs/exastro-gateway.pem
      SSLCertificateKeyFile /etc/pki/tls/private/exastro-gateway.key

      KeepAlive On
      OIDCResponseType code
      OIDCCryptoPassphrase {{ crypto_passphrase }}
      #OIDCCookieDomain example.com
      OIDCSSLValidateServer Off
      OIDCProviderMetadataURL http://{{ auth_host }}:{{ auth_port }}/auth/realms/{{ auth_realm }}/.well-known/openid-configuration
      OIDCPassClaimsAs headers
      
      RewriteEngine On
      RewriteOptions inherit
      
      OIDCRedirectURI  http://{{ client_host }}:{{ client_port }}/oidc-redirect/
      OIDCClientID {{ client_id }}
      OIDCClientSecret {{ client_secret }}
      <Location />
          ProxyPass        http://{{ app_ui_name }}.{{ app_namespace }}.svc:8000/
          ProxyPassReverse http://{{ app_ui_name }}.{{ app_namespace }}.svc:8000/
          AuthType openid-connect
          Require valid-user
      </Location>
      <Location /api/>
          ProxyPass        http://{{ app_api_name }}.{{ app_namespace }}.svc:8000/
          ProxyPassReverse http://{{ app_api_name }}.{{ app_namespace }}.svc:8000/
          AuthType openid-connect
          Require valid-user
      </Location>
      <Location /favicon.ico>
          Require all granted
      </Location>
    </VirtualHost>
