apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exastro-platform-authentication-infra-role
  namespace: exastro-platform-authentication-infra
rules:
 - apiGroups: ["apps"]
   resources: ["deployments"]
   verbs: ["get", "list", "watch", "create", "update", "patch"]
 - apiGroups: [""]
   resources: ["configmaps"]
   verbs: ["get", "list", "watch", "create", "update", "patch"]
 - apiGroups: [""]
   resources: ["services"]
   verbs: ["get", "list", "watch", "create", "update", "patch"]
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get", "list", "watch", "create", "update", "patch"]
 - apiGroups: [""]
   resources: ["pods/exec"]
   verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: exastro-platform-authentication-infra-rolebinding
 namespace: exastro-platform-authentication-infra
subjects:
- kind: ServiceAccount
  name: default
  namespace: exastro-platform-authentication-infra
roleRef:
  kind: Role
  name: exastro-platform-authentication-infra-role
  apiGroup: rbac.authorization.k8s.io
