apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nodeport-template
  namespace: exastro-platform-authentication-infra
data:
  nodeport-template.yaml: |
    apiVersion: v1
    kind: Service
    metadata:
      name: {{ client_id }}
      labels:
        app: {{ client_id }}
      namespace: {{ namespace }}
    spec:
      ports:
      - name: connection
        port: {{ port }}
        targetPort: {{ targetPort }}
        nodePort: {{ nodePort }}
      selector:
        name: {{ deploy_name }}
      type: NodePort